language: python
jobs:
  allow_failures:
    - osx_image: xcode12
  include:
    - name: "Python 3.5 on Linux"
      python: 3.5
      install:
        - make build-linux
        - pip install coveralls
    - name: "Python 3.8 on Linux"
      python: 3.8
      before_install:
        - make build-linux
        - pip install coveralls
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # macOS 10.14.6
      language: shell
      install:
        - sudo chmod 755 ninjadroid/aapt/aapt
        - sudo chmod 755 ninjadroid/apktool/apktool.jar
        - sudo chmod 755 ninjadroid/dex2jar/d2j-dex2jar.sh
        - pip3 install coverage
        - pip3 install pylint
        - pip3 install pyaxmlparser --user
        - pip3 install python-dateutil
        - pip3 install typing
        - pip3 install tzlocal
        - mv -f ninjadroid/aapt/aapt_macos ninjadroid/aapt/aapt
        - pip3 install coveralls
    - name: "Python 3.8.5 on macOS"
      os: osx
      osx_image: xcode12  # macOS 10.15.7
      language: shell
      install:
        - sudo chmod 755 ninjadroid/aapt/aapt
        - sudo chmod 755 ninjadroid/apktool/apktool.jar
        - sudo chmod 755 ninjadroid/dex2jar/d2j-dex2jar.sh
        - pip3 install coverage
        - pip3 install pylint
        - pip3 install pyaxmlparser --user
        - pip3 install python-dateutil
        - pip3 install typing
        - pip3 install tzlocal
        - mv -f ninjadroid/aapt/aapt_macos ninjadroid/aapt/aapt
        - pip3 install coveralls
script:
  - make checkstyle
  - make test-coverage
after_success:
  - coveralls