language: python
jobs:
  include:
    - name: "Python 3.5 on Linux"
      python: 3.5
      install:
        - make build-linux
        - pip install coveralls
    - name: "Python 3.8 on Linux"
      python: 3.8
      before_install:
        - make build-linux
        - pip install coveralls
    - name: "Python 3.8.6 on macOS"
      os: osx
      osx_image: xcode11.6  # macOS 10.15.5
      language: shell
      install:
        - make build-macos
        - pip3 install coveralls
script:
  - make checkstyle
  - make test-coverage
after_success:
  - coveralls
